import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Inter } from "next/font/google";
import Header from "./components/header";


const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Buy me a Pizza",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
        <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
              <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
